import { Country } from "@/types/Countries";

export const countries: Country[] = [
  {
    name: "Colombia",
    flag: "https://flagcdn.com/w320/co.png",
    alt: "The flag of Colombia is composed of three horizontal bands of yellow, blue and red, with the yellow band twice the height of the other two bands.",
    idd: {
      root: "+5",
      suffixes: ["7"],
    },
  },
  {
    name: "Curaçao",
    flag: "https://flagcdn.com/w320/cw.png",
    idd: {
      root: "+5",
      suffixes: ["99"],
    },
  },
  {
    name: "French Guiana",
    flag: "https://flagcdn.com/w320/gf.png",
    idd: {
      root: "+5",
      suffixes: ["94"],
    },
  },
  {
    name: "Grenada",
    flag: "https://flagcdn.com/w320/gd.png",
    alt: "The flag of Grenada features a large central rectangular area surrounded by a red border, with three five-pointed yellow stars centered on the top and bottom borders. The central rectangle is divided diagonally into four alternating triangular areas of yellow at the top and bottom and green on the hoist and fly sides, and a five-pointed yellow star on a red circle is superimposed at its center. A symbolic nutmeg pod is situated on the green hoist-side triangle.",
    idd: {
      root: "+1",
      suffixes: ["473"],
    },
  },
  {
    name: "Sint Maarten",
    flag: "https://flagcdn.com/w320/sx.png",
    idd: {
      root: "+1",
      suffixes: ["721"],
    },
  },
  {
    name: "Argentina",
    flag: "https://flagcdn.com/w320/ar.png",
    alt: "The flag of Argentina features three equal horizontal bands of light blue, white and light blue. A brown-edged golden sun is centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["4"],
    },
  },
  {
    name: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/w320/tc.png",
    idd: {
      root: "+1",
      suffixes: ["649"],
    },
  },
  {
    name: "Dominica",
    flag: "https://flagcdn.com/w320/dm.png",
    alt: "The flag of Dominica has a green field with a large centered tricolor cross. The vertical and horizontal parts of the cross each comprise three bands of yellow, black and white. A red circle, bearing a hoist-side facing purple Sisserou parrot standing on a twig and encircled by ten five-pointed yellow-edged green stars, is superimposed at the center of the cross.",
    idd: {
      root: "+1",
      suffixes: ["767"],
    },
  },
  {
    name: "United States Minor Outlying Islands",
    flag: "https://flagcdn.com/w320/um.png",
    idd: {
      root: "+2",
      suffixes: ["68"],
    },
  },
  {
    name: "Costa Rica",
    flag: "https://flagcdn.com/w320/cr.png",
    alt: "The flag of Costa Rica is composed of five horizontal bands of blue, white, red, white and blue. The central red band is twice the height of the other four bands.",
    idd: {
      root: "+5",
      suffixes: ["06"],
    },
  },
  {
    name: "Haiti",
    flag: "https://flagcdn.com/w320/ht.png",
    alt: "The flag of Haiti is composed of two equal horizontal bands of blue and red. A white square bearing the national coat of arms is superimposed at the center of the field.",
    idd: {
      root: "+5",
      suffixes: ["09"],
    },
  },
  {
    name: "Barbados",
    flag: "https://flagcdn.com/w320/bb.png",
    alt: "The flag of Barbados is composed of three equal vertical bands of ultramarine, gold and ultramarine. The head of a black trident is centered in the gold band.",
    idd: {
      root: "+1",
      suffixes: ["246"],
    },
  },
  {
    name: "Honduras",
    flag: "https://flagcdn.com/w320/hn.png",
    alt: "The flag of Honduras is composed of three equal horizontal bands of turquoise, white and turquoise, with five small five-pointed turquoise stars arranged in a quincuncial pattern at the center of the white band.",
    idd: {
      root: "+5",
      suffixes: ["04"],
    },
  },
  {
    name: "Puerto Rico",
    flag: "https://flagcdn.com/w320/pr.png",
    idd: {
      root: "+1",
      suffixes: ["787", "939"],
    },
  },
  {
    name: "Falkland Islands",
    flag: "https://flagcdn.com/w320/fk.png",
    idd: {
      root: "+5",
      suffixes: ["00"],
    },
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/w320/kn.png",
    alt: "The flag of Saint Kitts and Nevis features two large five-pointed white stars within a yellow-edged black diagonal band that extends from the lower hoist-side corner to the upper fly-side corner of the field. Above and beneath this band are a green and red triangle respectively.",
    idd: {
      root: "+1",
      suffixes: ["869"],
    },
  },
  {
    name: "Saint Lucia",
    flag: "https://flagcdn.com/w320/lc.png",
    alt: "The flag of Saint Lucia has a light blue field, at the center of which are two triangles which share a common base — a small golden-yellow isosceles triangle superimposed on a large white-edged black isosceles triangle.",
    idd: {
      root: "+1",
      suffixes: ["758"],
    },
  },
  {
    name: "Caribbean Netherlands",
    flag: "https://flagcdn.com/w320/bq.png",
    idd: {
      root: "+5",
      suffixes: ["99"],
    },
  },
  {
    name: "Bolivia",
    flag: "https://flagcdn.com/w320/bo.png",
    alt: "The flag of Bolivia is composed of three equal horizontal bands of red, yellow and green, with the national coat of arms centered in the yellow band.",
    idd: {
      root: "+5",
      suffixes: ["91"],
    },
  },
  {
    name: "Chile",
    flag: "https://flagcdn.com/w320/cl.png",
    alt: "The flag of Chile is composed of two equal horizontal bands of white and red, with a blue square of the same height as the white band superimposed in the canton. A white five-pointed star is centered in the blue square.",
    idd: {
      root: "+5",
      suffixes: ["6"],
    },
  },
  {
    name: "United States",
    flag: "https://flagcdn.com/w320/us.png",
    alt: "The flag of the United States of America is composed of thirteen equal horizontal bands of red alternating with white. A blue rectangle, bearing fifty small five-pointed white stars arranged in nine rows where rows of six stars alternate with rows of five stars, is superimposed in the canton.",
    idd: {
      root: "+1",
      suffixes: [
        "201",
        "202",
        "203",
        "205",
        "206",
        "207",
        "208",
        "209",
        "210",
        "212",
        "213",
        "214",
        "215",
        "216",
        "217",
        "218",
        "219",
        "220",
        "224",
        "225",
        "227",
        "228",
        "229",
        "231",
        "234",
        "239",
        "240",
        "248",
        "251",
        "252",
        "253",
        "254",
        "256",
        "260",
        "262",
        "267",
        "269",
        "270",
        "272",
        "274",
        "276",
        "281",
        "283",
        "301",
        "302",
        "303",
        "304",
        "305",
        "307",
        "308",
        "309",
        "310",
        "312",
        "313",
        "314",
        "315",
        "316",
        "317",
        "318",
        "319",
        "320",
        "321",
        "323",
        "325",
        "327",
        "330",
        "331",
        "334",
        "336",
        "337",
        "339",
        "346",
        "347",
        "351",
        "352",
        "360",
        "361",
        "364",
        "380",
        "385",
        "386",
        "401",
        "402",
        "404",
        "405",
        "406",
        "407",
        "408",
        "409",
        "410",
        "412",
        "413",
        "414",
        "415",
        "417",
        "419",
        "423",
        "424",
        "425",
        "430",
        "432",
        "434",
        "435",
        "440",
        "442",
        "443",
        "447",
        "458",
        "463",
        "464",
        "469",
        "470",
        "475",
        "478",
        "479",
        "480",
        "484",
        "501",
        "502",
        "503",
        "504",
        "505",
        "507",
        "508",
        "509",
        "510",
        "512",
        "513",
        "515",
        "516",
        "517",
        "518",
        "520",
        "530",
        "531",
        "534",
        "539",
        "540",
        "541",
        "551",
        "559",
        "561",
        "562",
        "563",
        "564",
        "567",
        "570",
        "571",
        "573",
        "574",
        "575",
        "580",
        "585",
        "586",
        "601",
        "602",
        "603",
        "605",
        "606",
        "607",
        "608",
        "609",
        "610",
        "612",
        "614",
        "615",
        "616",
        "617",
        "618",
        "619",
        "620",
        "623",
        "626",
        "628",
        "629",
        "630",
        "631",
        "636",
        "641",
        "646",
        "650",
        "651",
        "657",
        "660",
        "661",
        "662",
        "667",
        "669",
        "678",
        "681",
        "682",
        "701",
        "702",
        "703",
        "704",
        "706",
        "707",
        "708",
        "712",
        "713",
        "714",
        "715",
        "716",
        "717",
        "718",
        "719",
        "720",
        "724",
        "725",
        "727",
        "730",
        "731",
        "732",
        "734",
        "737",
        "740",
        "743",
        "747",
        "754",
        "757",
        "760",
        "762",
        "763",
        "765",
        "769",
        "770",
        "772",
        "773",
        "774",
        "775",
        "779",
        "781",
        "785",
        "786",
        "801",
        "802",
        "803",
        "804",
        "805",
        "806",
        "808",
        "810",
        "812",
        "813",
        "814",
        "815",
        "816",
        "817",
        "818",
        "828",
        "830",
        "831",
        "832",
        "843",
        "845",
        "847",
        "848",
        "850",
        "854",
        "856",
        "857",
        "858",
        "859",
        "860",
        "862",
        "863",
        "864",
        "865",
        "870",
        "872",
        "878",
        "901",
        "903",
        "904",
        "906",
        "907",
        "908",
        "909",
        "910",
        "912",
        "913",
        "914",
        "915",
        "916",
        "917",
        "918",
        "919",
        "920",
        "925",
        "928",
        "929",
        "930",
        "931",
        "934",
        "936",
        "937",
        "938",
        "940",
        "941",
        "947",
        "949",
        "951",
        "952",
        "954",
        "956",
        "959",
        "970",
        "971",
        "972",
        "973",
        "975",
        "978",
        "979",
        "980",
        "984",
        "985",
        "989",
      ],
    },
  },
  {
    name: "Guadeloupe",
    flag: "https://flagcdn.com/w320/gp.png",
    idd: {
      root: "+5",
      suffixes: ["90"],
    },
  },
  {
    name: "Mexico",
    flag: "https://flagcdn.com/w320/mx.png",
    alt: "The flag of Mexico is composed of three equal vertical bands of green, white and red, with the national coat of arms centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["2"],
    },
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/w320/vc.png",
    alt: "The flag of Saint Vincent and the Grenadines is composed of three vertical bands of blue, gold and green. The gold band is twice as wide as the other two bands and bears three green diamonds arranged to form the letter V at its center.",
    idd: {
      root: "+1",
      suffixes: ["784"],
    },
  },
  {
    name: "Bermuda",
    flag: "https://flagcdn.com/w320/bm.png",
    idd: {
      root: "+1",
      suffixes: ["441"],
    },
  },
  {
    name: "Dominican Republic",
    flag: "https://flagcdn.com/w320/do.png",
    alt: "The flag of the Dominican Republic is divided into four rectangles by a centered white cross that extends to the edges of the field and bears the national coat of arms in its center. The upper hoist-side and lower fly-side rectangles are blue and the lower hoist-side and upper fly-side rectangles are red.",
    idd: {
      root: "+1",
      suffixes: ["809", "829", "849"],
    },
  },
  {
    name: "Guatemala",
    flag: "https://flagcdn.com/w320/gt.png",
    alt: "The flag of Guatemala is composed of three equal vertical bands of light blue, white and light blue, with the national coat of arms centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["02"],
    },
  },
  {
    name: "Ecuador",
    flag: "https://flagcdn.com/w320/ec.png",
    alt: "The flag of Ecuador is composed of the horizontal bands of yellow, blue and red, with the yellow band twice the height of the other two bands. The Ecuadorian coat of arms is superimposed in the center of the field.",
    idd: {
      root: "+5",
      suffixes: ["93"],
    },
  },
  {
    name: "Martinique",
    flag: "https://flagcdn.com/w320/mq.png",
    idd: {
      root: "+5",
      suffixes: ["96"],
    },
  },
  {
    name: "Suriname",
    flag: "https://flagcdn.com/w320/sr.png",
    alt: "The flag of Suriname is composed of five horizontal bands of green, white, red, white and green in the ratio of 2:1:4:1:2. A large five-pointed yellow star is centered in the red band.",
    idd: {
      root: "+5",
      suffixes: ["97"],
    },
  },
  {
    name: "Saint Barthélemy",
    flag: "https://flagcdn.com/w320/bl.png",
    idd: {
      root: "+5",
      suffixes: ["90"],
    },
  },
  {
    name: "Bahamas",
    flag: "https://flagcdn.com/w320/bs.png",
    alt: "The flag of the Bahamas is composed of three equal horizontal bands of aquamarine, yellow and aquamarine, with a black equilateral triangle superimposed on the hoist side of the field. This triangle has its base on the hoist end and spans about one-third the width of the field.",
    idd: {
      root: "+1",
      suffixes: ["242"],
    },
  },
  {
    name: "Paraguay",
    flag: "https://flagcdn.com/w320/py.png",
    alt: "The flag of Paraguay features three equal horizontal bands of red, white and blue, with an emblem centered in the white band. On the obverse side of the flag depicted, this emblem is the national coat of arms.",
    idd: {
      root: "+5",
      suffixes: ["95"],
    },
  },
  {
    name: "British Virgin Islands",
    flag: "https://flagcdn.com/w320/vg.png",
    idd: {
      root: "+1",
      suffixes: ["284"],
    },
  },
  {
    name: "Brazil",
    flag: "https://flagcdn.com/w320/br.png",
    alt: "The flag of Brazil has a green field with a large yellow rhombus in the center. Within the rhombus is a dark blue globe with twenty-seven small five-pointed white stars depicting a starry sky and a thin white convex horizontal band inscribed with the national motto 'Ordem e Progresso' across its center.",
    idd: {
      root: "+5",
      suffixes: ["5"],
    },
  },
  {
    name: "Belize",
    flag: "https://flagcdn.com/w320/bz.png",
    alt: "The flag of Belize has a royal blue field with a thin red horizontal band at the top and bottom of the field and the national coat of arms in the center.",
    idd: {
      root: "+5",
      suffixes: ["01"],
    },
  },
  {
    name: "Venezuela",
    flag: "https://flagcdn.com/w320/ve.png",
    alt: "The flag of Venezuela is composed of three equal horizontal bands of yellow, blue and red. At the center of the blue band are eight five-pointed white stars arranged in a horizontal arc.",
    idd: {
      root: "+5",
      suffixes: ["8"],
    },
  },
  {
    name: "El Salvador",
    flag: "https://flagcdn.com/w320/sv.png",
    alt: "The flag of El Salvador is composed of three equal horizontal bands of cobalt blue, white and cobalt blue, with the national coat of arms centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["03"],
    },
  },
  {
    name: "Peru",
    flag: "https://flagcdn.com/w320/pe.png",
    alt: "The flag of Peru is composed of three equal vertical bands of red, white and red, with the national emblem centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["1"],
    },
  },
  {
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/w320/tt.png",
    alt: "The flag of Trinidad and Tobago has a red field with a white-edged black diagonal band that extends from the upper hoist-side corner to the lower fly-side corner of the field.",
    idd: {
      root: "+1",
      suffixes: ["868"],
    },
  },
  {
    name: "Greenland",
    flag: "https://flagcdn.com/w320/gl.png",
    idd: {
      root: "+2",
      suffixes: ["99"],
    },
  },
  {
    name: "Guyana",
    flag: "https://flagcdn.com/w320/gy.png",
    alt: "The flag of Guyana has a green field with two isosceles triangles which share a common base on the hoist end. The smaller black-edged red triangle spanning half the width of the field is superimposed on the larger white-edged yellow triangle which spans the full width of the field.",
    idd: {
      root: "+5",
      suffixes: ["92"],
    },
  },
  {
    name: "Jamaica",
    flag: "https://flagcdn.com/w320/jm.png",
    alt: "The flag of Jamaica is divided by a gold diagonal cross into four alternating triangular areas of green at the top and bottom, and black on the hoist and fly sides",
    idd: {
      root: "+1",
      suffixes: ["876"],
    },
  },
  {
    name: "Aruba",
    flag: "https://flagcdn.com/w320/aw.png",
    idd: {
      root: "+2",
      suffixes: ["97"],
    },
  },
  {
    name: "Cayman Islands",
    flag: "https://flagcdn.com/w320/ky.png",
    idd: {
      root: "+1",
      suffixes: ["345"],
    },
  },
  {
    name: "Cuba",
    flag: "https://flagcdn.com/w320/cu.png",
    alt: "The flag of Cuba is composed of five equal horizontal bands of blue alternating with white and a red equilateral triangle superimposed on the hoist side of the field. The triangle has its base on the hoist end, spans about two-fifth the width of the field and bears a white five-pointed star at its center.",
    idd: {
      root: "+5",
      suffixes: ["3"],
    },
  },
  {
    name: "Uruguay",
    flag: "https://flagcdn.com/w320/uy.png",
    alt: "The flag of Uruguay is composed of nine equal horizontal bands of white alternating with blue, with a white square superimposed in the canton. In the white square is a yellow sun bearing a human face — the Sun of May — from which sixteen rays extend. The sun's rays alternate between triangular and wavy.",
    idd: {
      root: "+5",
      suffixes: ["98"],
    },
  },
  {
    name: "Saint Martin",
    flag: "https://flagcdn.com/w320/mf.png",
    idd: {
      root: "+5",
      suffixes: ["90"],
    },
  },
  {
    name: "Antigua and Barbuda",
    flag: "https://flagcdn.com/w320/ag.png",
    alt: "The flag of Antigua and Barbuda has a red field with an inverted isosceles triangle based on the top edge and spanning the height of the field. This triangle has three horizontal bands of black, light blue and white, with the light blue band half the height of the two other bands. The top half of a golden-yellow sun is situated in the lower two-third of the black band to depict a rising sun.",
    idd: {
      root: "+1",
      suffixes: ["268"],
    },
  },
  {
    name: "Canada",
    flag: "https://flagcdn.com/w320/ca.png",
    alt: "The flag of Canada is composed of a red vertical band on the hoist and fly sides and a central white square that is twice the width of the vertical bands. A large eleven-pointed red maple leaf is centered in the white square.",
    idd: {
      root: "+1",
      suffixes: [""],
    },
  },
  {
    name: "Panama",
    flag: "https://flagcdn.com/w320/pa.png",
    alt: "The flag of Panama is composed of four equal rectangular areas — a white rectangular area with a blue five-pointed star at its center, a red rectangular area, a white rectangular area with a red five-pointed star at its center, and a blue rectangular area — in the upper hoist side, upper fly side, lower fly side and lower hoist side respectively.",
    idd: {
      root: "+5",
      suffixes: ["07"],
    },
  },
  {
    name: "Montserrat",
    flag: "https://flagcdn.com/w320/ms.png",
    idd: {
      root: "+1",
      suffixes: ["664"],
    },
  },
  {
    name: "Nicaragua",
    flag: "https://flagcdn.com/w320/ni.png",
    alt: "The flag of Nicaragua is composed of three equal horizontal bands of blue, white and blue, with the national coat of arms centered in the white band.",
    idd: {
      root: "+5",
      suffixes: ["05"],
    },
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/w320/pm.png",
    idd: {
      root: "+5",
      suffixes: ["08"],
    },
  },
  {
    name: "United States Virgin Islands",
    flag: "https://flagcdn.com/w320/vi.png",
    idd: {
      root: "+1",
      suffixes: ["340"],
    },
  },
  {
    name: "Anguilla",
    flag: "https://flagcdn.com/w320/ai.png",
    idd: {
      root: "+1",
      suffixes: ["264"],
    },
  },
] as const;
